baseURL = "https://phsd-phqmd.github.io/"
title = "PHSD-PHQMD"
DefaultContentLanguage = "en"
theme = "beautifulhugo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  subtitle = "A unified non-equilibrium microscopic transport approach for the description of the dynamics of strongly-interacting hadronic and partonic matter "
  logo = "img/PHSDPHQMD.png"
  favicon = "img/logo.ico"
  dateFormat = "October 19, 2021"
  custom_css = ["css/custom.css"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Download Code"
  url = "/code/"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 3

[[menu.main]]
  name = "Talks"
  url = "/talks/"
  weight = 4

[[menu.main]]
  name = "Team"
  url = "/team/"
  weight = 5
