baseurl = "https://phsd.github.io/"
title = "Parton-Hadron-String Dymanics"
# canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
# metaDataFormat = "yaml"
# pygmentsUseClasses = true
# pygmentCodeFences = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  subtitle = "A microscopic off-shell transport approach for Heavy-Ion Collisions"
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  dateFormat = "October 19, 2021"
  custom_css = ["css/custom.css"]
  # custom_js = ["js/custom.js"]
  # commit = false
  # comments = true

[[menu.main]]
  name = "About"
  url = "about"
  weight = 1

[[menu.main]]
  name = "Code"
  url = "code"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "publications"
  weight = 4

[[menu.main]]
  name = "Talks"
  url = "talks"
  weight = 4

[[menu.main]]
  name = "Team"
  url = "team"
  weight = 5